#ifndef _QPOTASSE_SHAPEDETECTOR_SHAPEDETECTOR_
#define _QPOTASSE_SHAPEDETECTOR_SHAPEDETECTOR_

class ShapeDetector {
   public:
   protected:
   private:
};
#endif  //_QPOTASSE_SHAPEDETECTOR_SHAPEDETECTOR_
